name: demo_server
version: 0.1.0
publish_to: none
description: Example package demonstrating MCP annotations and code generation.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dart_mcp: ^0.2.0
  mcp_annotations: ^0.1.0


dev_dependencies:
  build_runner: ^2.4.7
  mcp_codegen: ^0.1.0

dependency_overrides:
  mcp_annotations:
    path: ../../pkgs/mcp_annotations
  dart_mcp:
    path: ../../pkgs/dart_mcp
  mcp_codegen:
    path: ../../pkgs/mcp_codegen
