builders:
  mcp_builder:
    import: "package:mcp_codegen/mcp_codegen.dart"
    builder_factories: ["mcpBuilder"]
    build_extensions: {".dart": [".mcp.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"] 