name: mcp_codegen
version: 0.1.1
description: Source-gen builder that generates boilerplate MCP server and tool code.
repository: https://github.com/nelsoncampos-cloudwalk/mcp_dart_codegen/tree/main
homepage: https://github.com/nelsoncampos-cloudwalk/mcp_dart_codegen/tree/main

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^6.4.0
  build: ^2.4.0
  source_gen: ^1.5.0
  dart_mcp: ^0.2.0
  mcp_annotations: ^0.1.0
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.2 

dependency_overrides:
  mcp_annotations:
    path: ../mcp_annotations

