name: mcp_annotations
version: 0.1.0
description: Annotations for generating MCP server boilerplate and tools.
repository: https://github.com/nelsoncampos-cloudwalk/mcp_dart_codegen/tree/main
homepage: https://github.com/nelsoncampos-cloudwalk/mcp_dart_codegen/tree/main

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.11.0